version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: marynalytvynenko
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: mydatabase
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_USER=marynalytvynenko
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=mydatabase
    ports:
      - "5001:5000"  # Використовуємо порт 5001
    restart: unless-stopped

volumes:
  postgres_data: