# $$("input:visible")
# $$("input:read-write")
# $$("ul li:nth-child(3)")
# $$("ul li:nth-last-child(3)")
# $$("h2 + div#weatherLinks")
# $$("h2 ~ div#weatherLinks")
# $$("input:not(:enabled)")
# $$("div:not(#bd6)")
# $$("div:not(.main)")
# $$("a:not([href^='http'])")
# $$("li:first-child")
# $$("ul > li:first-child")
# $$("li:last-child")
# $$("h2:text('Heading 2')")
# $$("h2:text-is('Head')")
# $$("button:disabled")
# $$("input[type='checkbox']:checked")
# $$("input[type='radio']:checked")
# $$("a[target='_blank']")
# $$("div > p:first-of-type")
# $$("section:has(h2)")
# $$("div:has(> img)")
# $$("ul li:nth-of-type(2)")
# $$("form:has(input[name='email'])")
# $$("input[placeholder^='Enter']")