# $x('//h1')
# $x('//p[contains(text(), "hands-on experience")]')
# $x('//button[text()="Sign up"]')
# $x('//button[contains(@class, "header_signin")]')
# $x('//button[contains(text(), "Contacts")]')
# $x('//a[@routerlink="/" and text()="Home"]')
# $x('//nav//button[text()="About"]')
# $x('//nav//button[text()="Contacts"]')
# $x('//a[contains(@href, "ithillel.ua") and contains(@class, "display-4")]')
# $x('(//p[@class="about-block_title h2"])[1]')
# $x('//a[contains(@href, "facebook.com")]')
# $x('//a[contains(@href, "t.me/ithillel")]')
# $x('//p[text()="Log fuel expenses"]')
# $x('//p[text()="Keep track of your replacement schedule and plan your vehicle maintenance expenses in advance."]')
# $x('//p[text()="Instructions and manuals"]')
# $x('//p[contains(text(), "repair your car")]')
# $x('//div[@id="contactsSection"]')
# $x('//img[contains(@src, "info_1.jpg")]')
# $x('//footer//p[contains(text(), "educational purposes")]')
# $x('//p[contains(@class, "about-block_descr")]')
# $x('//div[contains(@class, "hero-video")]//iframe')
# $x('//a[contains(@class, "footer_logo")]')
# $x('//div[@class="app-wrapper"]')
# $x('//div[contains(@class, "contacts_socials")]')
# $x('//p[contains(text(), "repair your car")]')